### ISSUE TITLE
Give platform administrators wider visibility

### ISSUE THREAD

**Issue by bengerman13** [cloud-gov/kibana-cf-auth-proxy#4]
In order for platform administrators to manage settings and see all content, the proxy should note their group membership in UAA and set the proper roles. 

## Acceptance Criteria
* [ ] GIVEN a user is a member of groups in UAA \
  WHEN this proxy handles a request to Kibana \
  THEN their role is passed on to Opensearch as a header

--- 

## Security considerations

[note any potential changes to security boundaries, practices, documentation, risk that arise directly from this story]

## Implementation sketch

We should do this at the same time as we check the spaces a user has a role in. 

We probably pass this to Opensearch via `headers['x-proxy-roles']` [here](https://github.com/cloud-gov/kibana-cf-auth-proxy/blob/main/kibana_cf_auth_proxy/app.py#L162)

* [x] Add unit test for UAA group membership in `headers['x-proxy-roles']`
* [x] Add code to set UAA group membership as `headers['x-proxy-roles']`

**Comment by markdboyd** [comment]
Revised implementation:

- [ ] Use POST `/oauth/token` endpoint to get a token to act as the **client**, not the **user**. Use this token to make a request for user group data
- [ ] Use the [check membership endpoint](https://docs.cloudfoundry.org/api/uaa/version/4.8.0/index.html#check-membership) to determine if a user is a platform admin. If so, specify the `admin` role in `headers['x-proxy-roles']`.
