### ISSUE TITLE
Support multiple instances of the auth proxy

### ISSUE THREAD

**Issue by bengerman13** [cloud-gov/kibana-cf-auth-proxy#5]
In order to make the auth proxy resilient and scalable, we need to configure Flask to use a distributed session store.

## Acceptance Criteria
* [ ] GIVEN Flask is configured to use a distributed session store \
  WHEN  e2e tests are run \
  THEN passing tests confirm that distributed sessions are working

--- 

## Security considerations
[note any potential changes to security boundaries, practices, documentation, risk that arise directly from this story]

## Implementation sketch

This could be done with cryptographically-signed cookies or shared state such as Redis. Flask is flexible on that count.

Notes on using cryptographically-signed cookies for Flask: https://flask.palletsprojects.com/en/2.1.x/quickstart/#sessions

It appears that this approach is already mostly implemented, so we just need to:

* [x] Confirm that cryptographic cookie signing is implemented for Flask
* [x] Remove `flask_session` package from all requirements files
* [x] Delete this test: https://github.com/cloud-gov/kibana-cf-auth-proxy/blob/main/tests/unit/test_app.py#L63
* [x] Confirm that all tests are passing (unit and e2e)
* [x] Update e2e CF manifest for proxy tests to run multiple instances (2 is sufficient)
