### ISSUE TITLE
Update auth proxy dependencies/Docker images to latest versions of Opensearch

### ISSUE THREAD

**Issue by markdboyd** [cloud-gov/kibana-cf-auth-proxy#52]
## Acceptance criteria

- [x] Update https://github.com/cloud-gov/kibana-cf-auth-proxy/blob/main/docker/kibana/dockerfile to use latest version of Opensearch
- [x] Update https://github.com/cloud-gov/kibana-cf-auth-proxy/blob/main/docker/elasticsearch/dockerfile to use latest version of Opensearch
```[tasklist]
### Tasks
- [x] Update references to opensearch
- [x] update tests for opensearch
```
